export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST'
export const AUTH_TOKEN_SET = 'AUTH_TOKEN_SET'
export const AUTH_PROFILE_UPDATE = 'AUTH_PROFILE_UPDATE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const ON_APPLICATION_ERROR = 'ON_APPLICATION_ERROR'
