export const inputs = () => ({
  tenantInfoSection: {
    title: 'Tenant Info',
    inputType: 'section',
    span: 3,
  },
  firstName: {
    title: 'First Name',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  lastName: {
    title: 'Last Name',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  type: {
    title: 'Type',
    inputType: 'select',
    options: ['Co-Op', 'Apt'],
    error: '',
    required: false,
  },
  landlord: {
    title: 'Landlord',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  street: {
    title: 'Street',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  city: {
    title: 'City',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  state: {
    title: 'State',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  zip: {
    title: 'Zip',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  unit: {
    title: 'Unit',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  bedroom: {
    title: 'Bedroom',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  status: {
    title: 'Status',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  rentalPrice: {
    title: 'Rental Price',
    inputType: 'text',
    type: 'number',
    error: '',
    required: false,
  },
  propertyInfoSection: {
    title: 'Property Info',
    inputType: 'section',
    span: 3,
  },
  leaseStart: {
    title: 'Lease Start',
    inputType: 'text',
    type: 'date',
    error: '',
    required: false,
  },
  income1: {
    title: 'Income Range1',
    inputType: 'text',
    type: 'number',
    error: '',
    required: false,
  },
  income2: {
    title: 'Income Range2',
    inputType: 'text',
    type: 'number',
    error: '',
    required: false,
  },
  phone: {
    title: 'Phone',
    inputType: 'text',
    type: 'tel',
    error: '',
    required: false,
  },
  email: {
    title: 'Email',
    inputType: 'text',
    type: 'email',
    error: '',
    required: false,
  },
  description: {
    title: 'Description',
    inputType: 'text',
    type: 'text',
    error: '',
    required: false,
  },
  isActive: {
    title: 'Is Active',
    inputType: 'checkbox',
    error: '',
  },
  howManyPeople: {
    title: 'How Many People',
    inputType: 'text',
    type: 'number',
    error: '',
    required: false,
  },
  creditScore: {
    title: 'Credit Score',
    inputType: 'text',
    type: 'number',
    error: '',
    required: false,
  },
  hasPets: {
    title: 'Has Pet',
    inputType: 'checkbox',
    error: '',
  },
  viewingDate: {
    title: 'Viewing Date',
    inputType: 'text',
    type: 'date',
    error: '',
    required: false,
  },
  viewingTime: {
    title: 'Viewing Time',
    inputType: 'text',
    type: 'time',
    error: '',
    required: false,
  },
  area: {
    title: 'Area',
    inputType: 'text',
    type: 'string',
    error: '',
    required: false,
  },
  job: {
    title: 'Job',
    inputType: 'text',
    type: 'string',
    error: '',
    required: false,
  },
})